### ISSUE TITLE
А как прочитать атрибуты параметров?

### ISSUE THREAD

**Issue by kybarg** [sirian/php-yml-parser#4]
Посмотрел код, по моему парсер не умеет читать атрибуты элемента <param>

**Comment by sirian** [comment]
Атрибуты каких именно элементов? Offer?
На этот случай я добавил $offer->getXml(), который возвращает \SimpleXMLElement объект, и из него можно получить все дополнительные данные

**Comment by sirian** [comment]
Также есть метод `$offer->getAttribute`

**Comment by kybarg** [comment]
Спасибо, решено в новой версии.
Имелось ввиду поле `<param name="Цвет">...</param>`
